plugins {
    alias(libs.plugins.android.library)
}

android {
    signingConfigs {
        debug {
            storeFile = file('D:\\Working\\Projects\\Android\\KeyStores\\MyKey.jks')
            storePassword = '171719150'
            keyPassword = '171719150'
            keyAlias = 'MainKey'
        }
    }
    namespace 'com.vts.vtsapproot'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        minSdk = 24
        targetSdk = 37
        versionCode = 126091401
        versionName = "1.26.09.1401"

        signingConfig = signingConfigs.debug
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    allprojects {
        tasks.withType(JavaCompile).tap {
            configureEach {
                options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
            }
        }
    }
}

dependencies {
    // UI
    implementation libs.material
    implementation libs.rxandroid
    implementation libs.androidx.activity
    implementation libs.androidx.lifecycle.livedata
    implementation libs.androidx.lifecycle.viewmodel
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.swiperefreshlayout

    // shimmer
    implementation libs.shimmer

    // singledateandtimepicker
    implementation libs.singledateandtimepicker

    //google service
    implementation libs.androidx.credentials
    implementation libs.androidx.credentials.play.services.auth
    implementation libs.googleid
    implementation libs.integrity

    // Finger Print
    implementation libs.androidx.biometric

    // Retrofit
    implementation libs.retrofit
    implementation libs.picasso
    implementation libs.okhttp
    implementation libs.converter.gson
    implementation libs.converter.scalars
    implementation libs.logging.interceptor

    // camera
    implementation libs.barcode.scanning
    implementation libs.androidx.camera.core
    implementation libs.androidx.camera.camera2
    implementation libs.androidx.camera.lifecycle
    implementation libs.androidx.camera.view

    // ML Kit Text Recognition v2 - Latin script (supports Vietnamese)
    implementation(libs.text.recognition)

    // Android Image Cropper - To improve OCR accuracy
    implementation(libs.android.image.cropper)

    // photoview
    implementation libs.photoview
    implementation libs.glide
    annotationProcessor libs.compiler

    // Converter JSON (Gson)
    implementation(libs.gson)

    // firebase
    implementation(platform(libs.firebase.bom))
    implementation libs.firebase.messaging

    implementation libs.blurview
}
